### ISSUE TITLE
StarlingBase.java - transactionDateFormat using minutes instead of month

### ISSUE THREAD

**Issue by twstuart** [rzari/jarling#4]
StarlingBase.java - transactionDateFormat using minutes instead of month 
(yyyy-mm-dd -> YYYY-MM-dd).

PR has been submitted to resolve this.

**Comment by rzari** [comment]
Great, good spot and thanks for the PR.  Happy to add the contribution.md template.  Once the change has been pulled I'll provide an email address for the project.

Whilst I agree with correcting the pattern letters to 'MM', I can't see why we'd want to uppercase year to 'YYYY'?

**Comment by twstuart** [comment]
Probably right, I've updated the PR to lowercase year.

I've also found another issue, which I'll raise a separate issue for relating to the savings goals.

**Comment by rzari** [comment]
Perfect, accepted the pull request and merged in.  Closing this issue.  Thanks for spotting this, keep them coming.
